app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.choices import SelectField
from wtforms.fields.datetime import DateField
from wtforms.fields.numeric import IntegerField
from wtforms.fields.simple import PasswordField, SubmitField, StringField, HiddenField, TextAreaField
from wtforms.validators import DataRequired, Length, NumberRange


class ChangePasswordForm(FlaskForm):
    password = PasswordField("Password", validators=[
        DataRequired(message="You need to input password"),
        Length(min=8, max=16, message="Password needs to be 8 - 15 characters")
    ])
    newPassword = PasswordField("New Password", validators=[
        DataRequired(message="You need to input password"),
        Length(min=8, max=16, message="Password needs to be 8 - 15 characters")
    ])
    submit = SubmitField("Save")


class StudentProfileForm(FlaskForm):
    email = StringField("Email", validators=[
        DataRequired(message="You need to input email")
    ])
    phoneNumber = StringField("Phone number", validators=[
        DataRequired(message="You need to input phone number"),
        Length(max=11, message="The max of number needs to be 11 characters")
    ])
    address = StringField("Address", validators=[
        DataRequired(message="You need to input address"),
        Length(max=200, message="The max of address needs to be 200 characters")
    ])
    studentId = StringField("Student id", validators=[
        DataRequired(message="You need to input student id"),
        Length(max=20, message="Max is 20")
    ])
    dormBuilding = StringField("Dorm Building", validators=[
        DataRequired(message="You need to input dorm building number"),
        Length(max=50, message="Max is 50")
    ])
    dormRoom = StringField("Dorm room", validators=[
        DataRequired(message="You need to input dorm room number"),
        Length(max=10, message="Max is 10")
    ])
    submit = SubmitField("Save")


class TeacherProfileForm(FlaskForm):
    email = StringField("Email", validators=[
        DataRequired(message="You need to input email")
    ])
    phoneNumber = StringField("Phone number", validators=[
        DataRequired(message="You need to input phone number"),
        Length(max=11, message="The max of number needs to be 11 characters")
    ])
    address = StringField("Address", validators=[
        DataRequired(message="You need to input address"),
        Length(max=200, message="The max of address needs to be 200 characters")
    ])
    teacherId = StringField("Teacher id", validators=[
        DataRequired(message="You need to input Teacher id"),
        Length(max=20, message="Max is 20")
    ])
    officeLocation = StringField("Office location", validators=[
        DataRequired(message="You need to input office location"),
        Length(max=50, message="Max is 50")
    ])
    submit = SubmitField("Save")


class RestaurantStaffProfileForm(FlaskForm):
    email = StringField("Email", validators=[
        DataRequired(message="You need to input email")
    ])
    phoneNumber = StringField("Phone number", validators=[
        DataRequired(message="You need to input phone number"),
        Length(max=11, message="The max of number needs to be 11 characters")
    ])
    address = StringField("Address", validators=[
        DataRequired(message="You need to input address"),
        Length(max=200, message="The max of address needs to be 200 characters")
    ])
    workSchedule = StringField("Work schedule", validators=[
        DataRequired(message="You need to input work schedule"),
        Length(max=100, message="Max is 100")
    ])
    submit = SubmitField("Save")


class CreateModuleForm(FlaskForm):
    moduleName = StringField("Module Name", validators=[
        DataRequired(message="You need to input Module name"),
        Length(max=50, message="Max is 50")
    ])
    schedule = StringField("Schedule", validators=[
        DataRequired(message="You need to input schedule"),
        Length(max=50, message="Max is 50")
    ])
    location = StringField("Location", validators=[
        DataRequired(message="You need to input location"),
        Length(max=100, message="Max is 100")
    ])
    officeHours = StringField("Office Hours", validators=[
        DataRequired(message="You need to input office hours"),
        Length(max=100, message="Max is 100")
    ])
    submit = SubmitField("Save")


class EnrollForm(FlaskForm):
    submit = SubmitField("Enroll")


class CreateMenuForm(FlaskForm):
    date = DateField("Date", validators=[
        DataRequired("You need to input date")
    ])
    breakfast = StringField("Breakfast", validators=[
        DataRequired(message="You need to input breakfast"),
        Length(max=100, message="Max is 100")
    ])
    lunch = StringField("Lunch", validators=[
        DataRequired(message="You need to input lunch"),
        Length(max=100, message="Max is 100")
    ])
    dinner = StringField("Dinner", validators=[
        DataRequired(message="You need to input dinner"),
        Length(max=100, message="Max is 100")
    ])
    submit = SubmitField("Save")


class AnnouncementForm(FlaskForm):
    title = StringField("Title", validators=[
        DataRequired(message="You need to input title"),
        Length(max=200, message="Max is 200")
    ])
    content = TextAreaField("Content", validators=[
        DataRequired(message="You need to input content"),
        Length(max=500, message="Max is 500")
    ])
    submit = SubmitField("Save")


class MenuReviewForm(FlaskForm):
    rating = IntegerField("Rating: 1-5", validators=[
        DataRequired(),
        NumberRange(min=1, max=5, message="Rating must be between 1 and 5")
    ])
    reviewContent = TextAreaField("Review Content", validators=[
        DataRequired(message="You need to input review content"),
        Length(max=500, message="Max is 500")
    ])
    submit = SubmitField("Save")

app/main/__init__.py
from flask import Blueprint

# Used to definite the main parts

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import logging
import os

import requests
from flask import redirect, url_for, flash, render_template, request, jsonify, current_app
from flask_login import current_user, login_user, logout_user, login_required
from pyexpat.errors import messages
from sqlalchemy import false
from werkzeug.security import generate_password_hash, check_password_hash

from app import db
from app.main import bp
from app.main.forms import ChangePasswordForm, MenuReviewForm, CreateMenuForm, EnrollForm, StudentProfileForm, \
    TeacherProfileForm, RestaurantStaffProfileForm, CreateModuleForm, AnnouncementForm
from app.models import *


@bp.route("/")
@bp.route("/index")
def index():
    # Use paging to display courses in pages
    currentPage = request.args.get("page", 1, type=int)
    currentPageAnnouncements = Announcement.query.order_by(Announcement.createTime.desc()).paginate(page=currentPage,
                                                                                                    per_page=10,
                                                                                                    error_out=False)
    announcements = currentPageAnnouncements.items
    return render_template("main/index.html", announcements=announcements,
                           currentPageAnnouncements=currentPageAnnouncements)


@bp.route("/announcement/<int:announcementId>")
def announcement(announcementId):
    announcement = Announcement.query.filter(Announcement.id == announcementId).first()
    if not announcement:
        return redirect(url_for("main.wrongPage"))
    return render_template("main/announcement.html", announcement=announcement)


@bp.route("/profile")
@login_required
def profile():
    return render_template("main/profile.html", user=current_user)


@bp.route("/deleteReview/<int:reviewId>", methods=["DELETE"])
@login_required
def deleteReview(reviewId):
    if current_user.role != "student" and current_user.role != "teacher":
        flash("You can not do that")
        return redirect(url_for("main.index"))

    review = MenuReview.query.filter(MenuReview.id == reviewId).first()
    if not review:
        return redirect(url_for("main.wrongPage"))

    logging.getLogger("menu").info(f"{current_user.username} delete a menu review, content: {review.reviewContent}")

    db.session.delete(review)
    db.session.commit()

    return jsonify({"message": "Successful delete!"})


@bp.route("/deleteAccount", methods=["DELETE"])
@login_required
def deleteAccount():
    user = User.query.filter(User.id == current_user.id).first()

    if not user:
        return redirect(url_for("main.wrongPage"))

    if current_user.role == "student":
        # Delete modules and reviews
        StudentModule.query.filter(StudentModule.studentId == user.id).delete()
        Student.query.filter(Student.userId == user.id).delete()
        MenuReview.query.filter(MenuReview.userId == user.id).delete()
        db.session.delete(user)
        db.session.commit()
    elif current_user.role == "teacher":
        # Delete reviews and modules
        modules = Module.query.filter(Module.teacherId == user.id)

        for module in modules:
            module.teacherId = None
        db.session.commit()

        Teacher.query.filter(Teacher.userId == user.id).delete()
        MenuReview.query.filter(MenuReview.userId == user.id).delete()
        db.session.delete(user)
        db.session.commit()
    elif current_user.role == "restaurantStaff":
        # Delete menus
        menus = Menu.query.filter(Menu.createdBy == user.id)

        for menu in menus:
            menu.createdBy = None
        db.session.commit()

        RestaurantStaff.query.filter(RestaurantStaff.userId == user.id).delete()
        db.session.delete(user)
        db.session.commit()
    else:
        db.session.delete(user)
        db.session.commit()

    logging.getLogger("account").info(f"{current_user.username} delete his/her account")

    return jsonify({"message": "Successful delete!"})


@bp.route("/editProfile", methods=["GET", "POST"])
@login_required
def editProfile():
    if current_user.role == "admin":
        return redirect(url_for("main.wrongPage"))

    if current_user.role == "student":
        form = StudentProfileForm()
        if form.validate_on_submit():
            # Find if there is a student with the same id
            checkId = Student.query.filter(Student.studentId == form.studentId.data).first()
            if checkId and current_user.student.studentId != checkId.studentId:
                flash("This id is already register, change it")
                return redirect(url_for("main.editProfile"))

            # Find if there is a student with the same email
            checkEmail = User.query.filter(User.email == form.email.data).first()
            if checkEmail and current_user.email != checkEmail.email:
                flash("This email is already register, change it")
                return redirect(url_for("main.editProfile"))

            # Find if there is a student with the same phone
            checkPhone = User.query.filter(User.phoneNumber == form.phoneNumber.data).first()
            if checkPhone and current_user.phoneNumber != checkPhone.phoneNumber:
                flash("This phone number is already register, change it")
                return redirect(url_for("main.editProfile"))

            current_user.email = form.email.data
            current_user.phoneNumber = form.phoneNumber.data
            current_user.address = form.address.data
            current_user.student.studentId = form.studentId.data
            current_user.student.dormBuilding = form.dormBuilding.data
            current_user.student.dormRoom = form.dormRoom.data
            db.session.commit()
            flash("Successful saved")

            logging.getLogger("account").info(f"{current_user.username} edit his/her profile")

            return redirect(url_for("main.profile"))
        form.email.data = current_user.email
        form.phoneNumber.data = current_user.phoneNumber
        form.address.data = current_user.address
        form.studentId.data = current_user.student.studentId
        form.dormBuilding.data = current_user.student.dormBuilding
        form.dormRoom.data = current_user.student.dormRoom
        return render_template("main/editProfile.html", form=form)
    elif current_user.role == "teacher":
        form = TeacherProfileForm()
        if form.validate_on_submit():
            # Find if there is a teacher with the same id
            checkId = Teacher.query.filter(Teacher.teacherId == form.teacherId.data).first()
            if checkId and current_user.teacher.teacherId != checkId.teacherId:
                flash("This id is already register, change it")
                return redirect(url_for("main.editProfile"))

            # Find if there is a teacher with the same email
            checkEmail = User.query.filter(User.email == form.email.data).first()
            if checkEmail and current_user.email != checkEmail.email:
                flash("This email is already register, change it")
                return redirect(url_for("main.editProfile"))

            # Find if there is a teacher with the same phone
            checkPhone = User.query.filter(User.phoneNumber == form.phoneNumber.data).first()
            if checkPhone and current_user.phoneNumber != checkPhone.phoneNumber:
                flash("This phone number is already register, change it")
                return redirect(url_for("main.editProfile"))

            current_user.email = form.email.data
            current_user.phoneNumber = form.phoneNumber.data
            current_user.address = form.address.data
            current_user.teacher.teacherId = form.teacherId.data
            current_user.teacher.officeLocation = form.officeLocation.data
            db.session.commit()
            flash("Successful saved")

            logging.getLogger("account").info(f"{current_user.username} edit his/her profile")

            return redirect(url_for("main.profile"))
        form.email.data = current_user.email
        form.phoneNumber.data = current_user.phoneNumber
        form.address.data = current_user.address
        form.teacherId.data = current_user.teacher.teacherId
        form.officeLocation.data = current_user.teacher.officeLocation
        return render_template("main/editProfile.html", form=form)
    elif current_user.role == "restaurantStaff":
        form = RestaurantStaffProfileForm()
        if form.validate_on_submit():
            # Find if there is a restaurant staff with the same email
            checkEmail = User.query.filter(User.email == form.email.data).first()
            if checkEmail and current_user.email != checkEmail.email:
                flash("This email is already register, change it")
                return redirect(url_for("main.editProfile"))

            # Find if there is a restaurant staff with the same phone
            checkPhone = User.query.filter(User.phoneNumber == form.phoneNumber.data).first()
            if checkPhone and current_user.phoneNumber != checkPhone.phoneNumber:
                flash("This phone number is already register, change it")
                return redirect(url_for("main.editProfile"))

            current_user.email = form.email.data
            current_user.phoneNumber = form.phoneNumber.data
            current_user.address = form.address.data
            current_user.restaurantStaff.workSchedule = form.workSchedule.data
            db.session.commit()
            flash("Successful saved")

            logging.getLogger("account").info(f"{current_user.username} edit his/her profile")

            return redirect(url_for("main.profile"))
        form.email.data = current_user.email
        form.phoneNumber.data = current_user.phoneNumber
        form.address.data = current_user.address
        form.workSchedule.data = current_user.restaurantStaff.workSchedule

app/templates/main/admin.html
{% extends "main/base.html" %}
{% block title %}
    Admin
{% endblock %}

{% block content %}
    <h2>Admin</h2>

    <div class="adminOption">

        <div class="card">
            <a href="{{ url_for("admin.announcements") }}">View announcements</a>
        </div>

        <div class="card">
            <a href="{{ url_for("admin.menus") }}">View menus</a>
        </div>

        <div class="card">
            <a href="{{ url_for("admin.modules") }}">View modules</a>
        </div>

        <div class="card">
            <a href="{{ url_for("admin.users") }}">View users</a>
        </div>

    </div>


    <hr>


    <h2>Log parts</h2>


    <div class="adminOption">

        <div class="card">
            <a href="{{ url_for("admin.accountLog") }}">Account Log</a>
        </div>

        <div class="card">
            <a href="{{ url_for("admin.announcementLog") }}">Announcement Log</a>
        </div>

        <div class="card">
            <a href="{{ url_for("admin.errorLog") }}">Error Log</a>
        </div>

        <div class="card">
            <a href="{{ url_for("admin.loginLog") }}">Login Log</a>
        </div>

    </div>

    <hr>

        <div class="adminOption">

        <div class="card">
            <a href="{{ url_for("admin.menuLog") }}">Menu Log</a>
        </div>

        <div class="card">
            <a href="{{ url_for("admin.moduleLog") }}">Module Log</a>
        </div>

        <div class="card">
            <a href="{{ url_for("admin.registerLog") }}">Register Log</a>
        </div>

    </div>

{% endblock %}

app/templates/main/announcement.html
{% extends "main/base.html" %}
{% block title %}
    {{ announcement.title }}
{% endblock %}

{% block content %}
	<h2 class="detailTitle">{{ announcement.title }}</h2>
    <p class="detailDate">{{ announcement.createTime }}</p>
    <hr>
    <p class="detailContent">{{ announcement.content }}</p>
{% endblock %}

app/templates/main/banPage.html
{% extends "main/base.html" %}
{% block title %}
    Ban page
{% endblock %}

{% block content %}
	<h2 class="detailTitle">You have benn Banned</h2>
{% endblock %}

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        School Web
    {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for("static", filename="iconfont/iconfont.css") }}">
    <link rel="stylesheet" href="{{ url_for("static", filename="css/base.css") }}">
    <link rel="stylesheet" href="{{ url_for("static", filename="css/itemList.css") }}">
    <link rel="stylesheet" href="{{ url_for("static", filename="css/form.css") }}">
    <link rel="stylesheet" href="{{ url_for("static", filename="css/itemDetail.css") }}">
    <link rel="stylesheet" href="{{ url_for("static", filename="css/chat.css") }}">
    <link rel="stylesheet" href="{{ url_for("static", filename="css/main.css") }}">
</head>
<body>

{# To load the theme first #}
<script src="{{ url_for("static", filename="js/mode.js") }}"></script>
{# Initial set to light mode #}
<header>

    <a href="#" class="webTitle"><span>Welcome to school web</span></a>

    <nav>
        <a href="{{ url_for("main.index") }}">Home</a>
        <a href="{{ url_for("main.modules") }}">Modules</a>
        <a href="{{ url_for("main.menus") }}">Menus</a>
        {#  Add navigation options based on different roles and whether logged in  #}
        {% if current_user.is_authenticated %}

            {#            Administrators do not need to edit personal information#}

            {% if current_user.role != "admin" %}
                <a href="{{ url_for("main.profile") }}">Profile</a>
                <a href="{{ url_for("main.editProfile") }}">Edit Profile</a>
            {% endif %}

            {% if current_user.role == "teacher" %}
                <a href="{{ url_for("main.createModule") }}">Create Module</a>
                <a href="{{ url_for("main.createAnnouncement") }}">Create Announcement</a>
            {% elif current_user.role == "restaurantStaff" %}
                <a href="{{ url_for("main.createMenu") }}">Create Menu</a>
            {% elif current_user.role == "admin" %}
                <a href="{{ url_for("main.admin") }}">Admin</a>
            {% endif %}
            <a href="{{ url_for("auth.logout") }}">Logout</a>
        {% else %}
            <a href="{{ url_for("auth.login") }}">Login</a>
            <a href="{{ url_for("auth.register") }}">Register</a>
        {% endif %}
        <a href="#" class="toggleTheme"><span class="iconfont icon-SUN"></span></a>
    </nav>

</header>

<div class="info">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="flash">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% block content %}

    {% endblock %}

    <div class="chat">
        <div class="header">
            <div class="logo">
                <span class="iconfont icon-robot"></span>
            </div>
            <div class="title">
                ChatBot
            </div>
            <div class="close">
                X
            </div>
        </div>

        <div class="body">
            <div class="fromBot">
                <div class="text">
                    Hello, what can i help you today?
                </div>
            </div>
        </div>

        <div class="footer">
            <form action="#" class="textForm">
                <textarea placeholder="Message..."></textarea>
                <div class="send"><span class="iconfont icon-Send"></span></div>
            </form>
        </div>
    </div>

    <div class="openBot">
        <div class="logo">
            <span class="iconfont icon-robot"></span>
        </div>
    </div>
</div>


<footer>
    {# Copyright Information #}
    <p>&copy;Gruop 12</p>

</footer>

<script src="{{ url_for("static", filename="js/base.js") }}"></script>
<script src="{{ url_for("static", filename="js/admin.js") }}"></script>
<script src="{{ url_for("static", filename="js/chat.js") }}"></script>
<script src="{{ url_for("static", filename="js/main.js") }}"></script>
<script src="{{ url_for("static", filename="js/register.js") }}"></script>
<script src="{{ url_for("static", filename="js/editProfile.js") }}"></script>
<script src="{{ url_for("static", filename="js/removeOption.js") }}"></script>
<script src="{{ url_for("static", filename="js/editModule.js") }}"></script>
<script src="{{ url_for("static", filename="js/updateCardImg.js") }}"></script>
<script src="{{ url_for("static", filename="js/menuDate.js") }}"></script>

</body>
</html>

app/templates/main/changePassword.html
{% extends "main/base.html" %}
{% block title %}
    Change password
{% endblock %}

{% block content %}
    <h2 class="formTitle">Change your password</h2>
    <form method="post">

        {{ form.hidden_tag() }}

        <p class="form">
            {{ form.password.label }} :
            {{ form.password() }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="form">
            {{ form.newPassword.label }} :
            {{ form.newPassword }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="formSubmit">
            {{ form.submit() }}
        </p>

    </form>
{% endblock %}

app/templates/main/createAnnouncement.html
{% extends "main/base.html" %}
{% block title %}
    Create announcement
{% endblock %}

{% block content %}
    <h2 class="formTitle">Create announcement</h2>

    <form method="post">

        {{ form.hidden_tag() }}

        <p class="form">
            {{ form.title.label }} :
            {{ form.title }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="form">
            {{ form.content.label }} : <br>
            {{ form.content }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="formSubmit">
            {{ form.submit }}
        </p>

    </form>
{% endblock %}

app/templates/main/createMenu.html
{% extends "main/base.html" %}
{% block title %}
    Create Menu
{% endblock %}

{% block content %}
    <h2 class="formTitle">Create Menu</h2>
    <form method="post">

        {{ form.hidden_tag() }}

        <p class="form">
            {{ form.date.label }} :
            {{ form.date(id = "menuDate") }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="form">
            {{ form.breakfast.label }} :
            {{ form.breakfast }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="form">
            {{ form.lunch.label }} :
            {{ form.lunch }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="form">
            {{ form.dinner.label }} :
            {{ form.dinner }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="formSubmit">
            {{ form.submit }}
        </p>

    </form>
{% endblock %}

app/templates/main/createModule.html
{% extends "main/base.html" %}
{% block title %}
    Create Module
{% endblock %}

{% block content %}
    <h2 class="formTitle">Create Module</h2>
    <form method="post">

        {{ form.hidden_tag() }}

        <p class="form">
            {{ form.moduleName.label }} :
            {{ form.moduleName }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="form">
            {{ form.schedule.label }} :
            {{ form.schedule }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="form">
            {{ form.location.label }} :
            {{ form.location }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="form">
            {{ form.officeHours.label }} :
            {{ form.officeHours }} <br>
            <span class="errorMsg"></span>
        </p>

        <p class="formSubmit">
            {{ form.submit }}
        </p>

    </form>
{% endblock %}

app/templates/main/editProfile.html
{% extends "main/base.html" %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}
    <h2 class="formTitle">Edit your profile</h2>
    <form method="post" id="userEditSubmit">

        {{ form.hidden_tag() }}
        <p class="form">
            {{ form.email.label }} :
            {{ form.email(id = "userEditEmail") }} <br>
            <span class="errorMsg" id="errorEserEditEmail"></span>
        </p>
        <p class="form">
            {{ form.phoneNumber.label }} :
            {{ form.phoneNumber(id = "userEditPhone") }} <br>
            <span class="errorMsg" id="errorEserEditPhone"></span>
        </p>
        <p class="form">
            {{ form.address.label }} :
            {{ form.address }} <br>
            <span class="errorMsg"></span>
        </p>

        {% if current_user.role == "student" %}
            <p class="form">
                {{ form.studentId.label }} :
                {{ form.studentId(id = "userEditStudentId") }} <br>
                <span class="errorMsg" id="errorUserEditStudentId"></span>
            </p>
            <p class="form">
                {{ form.dormBuilding.label }} :
                {{ form.dormBuilding }} <br>
                <span class="errorMsg"></span>
            </p>
            <p class="form">
                {{ form.dormRoom.label }} :
                {{ form.dormRoom }} <br>
                <span class="errorMsg"></span>
            </p>
        {% elif current_user.role == "teacher" %}
            <p class="form">
                {{ form.teacherId.label }} :
                {{ form.teacherId(id = "userEditTeacherId") }} <br>
                <span class="errorMsg" id="errorUserEditTeacherId"></span>
            </p>
            <p class="form">
                {{ form.officeLocation.label }} :
                {{ form.officeLocation }} <br>
                <span class="errorMsg"></span>
            </p>
        {% elif current_user.role == "restaurantStaff" %}
            <p class="form">
                {{ form.workSchedule.label }} :
                {{ form.workSchedule }} <br>
                <span class="errorMsg"></span>
            </p>
        {% endif %}
        <p class="formSubmit">
            {{ form.submit() }}
        </p>
    </form>
{% endblock %}

app/templates/main/index.html
{% extends "main/base.html" %}
{% block title %}
    Home
{% endblock %}

{% block content %}

    <div class="slide">

        <img src="../../static/images/bg1.png" alt="background picture">
        <div class="prev">
            &lt;
        </div>
        <div class="next">
            &gt;
        </div>

    </div>

    {% if announcements %}
        <div class="announcementList">
            <h2 class="pageTitle">Announcements: </h2>
            <ul class="pageList">
                {% for announcement in announcements %}
                    <li class="annItem">
                        <a href="{{ url_for("main.announcement", announcementId=announcement.id) }}">{{ announcement.title }}</a>
                    </li>
                {% endfor %}

            </ul>
        </div>
    {% endif %}

    <div class="page">

        {% if currentPageAnnouncements.has_prev %}
            <a href="{{ url_for("main.index", page=currentPageAnnouncements.prev_num) }}" class="prev">Prev</a>
        {% endif %}
        <span>Current page: {{ currentPageAnnouncements.page }}</span>
        {% if currentPageAnnouncements.has_next %}
            <a href="{{ url_for("main.index", page=currentPageAnnouncements.next_num) }}" class="next">Next</a>
        {% endif %}

    </div>

    <hr>

    <h2 class="pageTitle">About us: </h2>

    <div class="about">
        <div class="person">
            <div class="photo">
                <img src="../../static/images/shz.png">
                <div class="personName">
                    Haozhe Sun
                </div>
            </div>
            <div class="intro">
                Responsible for UI design and administrator parts
            </div>
        </div>

        <div class="person">
            <div class="intro">
                Responsible for backend routing design and beautification of the interface
            </div>
            <div class="photo">
                <img src="../../static/images/ysc.png">
                <div class="personName">
                    Sicheng Yi
                </div>
            </div>
        </div>

        <div class="person">
            <div class="photo">
                <img src="../../static/images/wzh.png">
                <div class="personName">
                    Ziheng Wang
                </div>
            </div>
            <div class="intro">
                Responsible for some basic function implementation and AJAX interaction
            </div>
        </div>
    </div>

{% endblock %}